### ISSUE TITLE
add GH Pages deploy GH action

### ISSUE THREAD

**Issue by shazron** [AdobeDocs/gatsby-theme-parliament-platform#3]
https://github.com/adobe/aio-cli-plugin-doc/blob/master/src/generator/templates/.github/workflows/github-pages.yml
make sure the default branch is correct in the script

**Comment by icaraps** [comment]
@shazron  I think https://github.com/adobe/aio-cli-plugin-doc/blob/master/src/generator/templates/.github/workflows/github-pages.yml#L4 should be `main` now

**Comment by shazron** [comment]
@icaraps yup I will be updating those first
